# Site settings
title: ELIFKULA
description:

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Encoding
encoding: utf-8

# Turkish timezone
timezone: Europe/Istanbul

# Exclude from build
exclude:
  - design.md
  - README.md
  - Gemfile
  - Gemfile.lock

url: "https://elifnkula.com.tr"
baseurl: ""
